version: '3'
services:
  frontend:
    build: .
    hostname: frontend
    ports: 
      - "8095:8080"
    volumes: 
      - .:/home/node/app:rw
    restart: "no"
    command: sh
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true